USE CursoSQL

SELECT *
FROM PRODUCTOS
INNER JOIN MARCAS ON PRODUCTOS.MARCA_ID = MARCAS.ID;

SELECT P.ID, P.NOMBRE_PRODUCTO, M.ID, M.NOMBRE_MARCA
FROM PRODUCTOS P
INNER JOIN MARCAS M ON P.MARCA_ID = M.ID;

SELECT *
FROM PRODUCTOS
RIGHT JOIN MARCAS ON PRODUCTOS.MARCA_ID = MARCAS.ID;

SELECT P.ID, P.NOMBRE_PRODUCTO, M.ID, M.NOMBRE_MARCA
FROM PRODUCTOS P
RIGHT JOIN MARCAS M ON P.MARCA_ID = M.ID;

SELECT P.ID, P.NOMBRE_PRODUCTO, M.ID, M.NOMBRE_MARCA
FROM PRODUCTOS P
LEFT JOIN MARCAS M ON P.MARCA_ID = M.ID;

SELECT *
FROM PRODUCTOS
LEFT JOIN MARCAS ON PRODUCTOS.MARCA_ID = MARCAS.ID;

SELECT P.ID, P.NOMBRE_PRODUCTO, M.ID, M.NOMBRE_MARCA
FROM PRODUCTOS P
FULL JOIN MARCAS M ON P.MARCA_ID = M.ID;
