--SELECT COURSEID, COUNT(STUDENTID)
--FROM STUDENT_COURSES
--GROUP BY COURSEID
--HAVING COUNT(STUDENTID) >= 1;


--SELECT sum(SALARY) AS 'Salary'
--FROM INSTRUCTORS

--suma y calcula el promedio
--SELECT sum(SALARY) AS 'SALARY' , avg(salary) AS 'AVG'
--FROM INSTRUCTORS

--SELECT COURSEID, COUNT(*)
--FROM STUDENT_COURSES
--GROUP BY COURSEID
--HAVING COUNT(*) < 3;


SELECT CASE WHEN AGE BETWEEN 20 AND 23 THEN 'TEAM 1' ELSE 'TEAM 2' END
FROM STUDENTS
GROUP BY AGE
