--SELECT * FROM dbo.STUDENT_COURSES;
--SELECT * FROM dbo.STUDENTS;
--SELECT * FROM dbo.COURSES;


-- ORDENADO DE FORMA DESENDENTE 
SELECT EMAIL, FIRSTNAME
FROM dbo.INSTRUCTORS
ORDER BY LOADDATE DESC

--ORDENADO DE FORMA ASCENDENTE 
SELECT EMAIL, FIRSTNAME
FROM dbo.INSTRUCTORS
ORDER BY LOADDATE ASC