--SELECT COURSEID, COUNT(STUDENTID)
--FROM STUDENT_COURSES
--GROUP BY COURSEID
--HAVING COUNT(STUDENTID) >= 1;


--SELECT sum(SALARY) AS 'Salary'
--FROM INSTRUCTORS

--suma y calcula el promedio
--SELECT sum(SALARY) AS 'SALARY' , avg(salary) AS 'AVG'
--FROM INSTRUCTORS