USE CursoSQL;

UPDATE COURSES
SET COURSENAME = 'Introduction to MySQL'
WHERE COURSENAME = 'Introduction to SQL'


UPDATE dbo.INSTRUCTORS
SET SPECIALIZATION = CASE INSTRUCTORID
    WHEN 1 THEN 'Mathematics'
    WHEN 2 THEN 'Physics'
    WHEN 3 THEN 'Computer Science'
    WHEN 4 THEN 'Chemistry'
    WHEN 5 THEN 'Biology'
    WHEN 6 THEN 'English'
END,
SALARY = CASE INSTRUCTORID
    WHEN 1 THEN 60000
    WHEN 2 THEN 65000
    WHEN 3 THEN 70000
    WHEN 4 THEN 62000
    WHEN 5 THEN 58000
    WHEN 6 THEN 55000
END
WHERE INSTRUCTORID BETWEEN 1 AND 6;


SELECT * FROM COURSES

